#ifndef DEVICE_DEFINITION_H
#define DEVICE_DEFINITION_H

#include <stdint.h>

struct device_metadata_t {
	uint8_t type;
	uint8_t id;
};

/**
 * Device type enumeration.
 */
#define DEVICE_TYPE_NULL 0x00
#define DEVICE_TYPE_RESERVED_1 0x01
#define DEVICE_TYPE_RESERVED_2 0x02
#define DEVICE_TYPE_RESERVED_3 0x03
#define DEVICE_TYPE_RESERVED_4 0x04
#define DEVICE_TYPE_RESERVED_5 0x05
#define DEVICE_TYPE_IRRIGATION 0x06
#define DEVICE_TYPE_POWEROUTLET 0x07
#define DEVICE_TYPE_THERMOSTAT 0x08
#define DEVICE_TYPE_CAMERA 0x09

/**
 * Attributes common to all devices.
 */
#define GENERIC_ATTR_NULL 0x01
#define GENERIC_ATTR_RESERVED_1 0x01
#define GENERIC_ATTR_RESERVED_2 0x02
#define GENERIC_ATTR_RESERVED_3 0x03
#define GENERIC_ATTR_RESERVED_4 0x04
#define GENERIC_ATTR_RESERVED_5 0x05
#define GENERIC_ATTR_ENABLE 0x06
#define GENERIC_ATTR_PING 0x07
// #define GENERIC_ATTR_KEEPALIVE 0x08
// #define GENERIC_ATTR_DATE 0x09
// #define GENERIC_ATTR_TIME 0x0A
// #define GENERIC_ATTR_WEEKDAY 0x0B 
// #define GENERIC_ATTR_SCHEDULE 0x0C
// #define GENERIC_ATTR_SCHEDULE_ENABLE 0x0D
// #define GENERIC_ATTR_SCHEDULE_COUNT 0x0E
#define GENERIC_ATTR_BLINK 0x0F
#define GENERIC_ATTR_APP_INTERVAL 0x10
// #define GENERIC_ATTR_POLL_INTERVAL 0x11
// #define GENERIC_ATTR_PUSH_ENABLE 0x12
// #define GENERIC_ATTR_PUSH_INTERVAL 0x13
// #define GENERIC_ATTR_PUSH_BUFFERING 0x14
#define GENERIC_ATTR_RESET_CONFIGS 0x15
#define GENERIC_ATTR_LOG_LEVEL 0x16


/**
 *Device-specific attribuets. 
 */
#define POWEROUTLET_ATTR_STATE 0x80
#define POWEROUTLET_ATTR_SOCKET_COUNT 0x81

#define THERMOSTAT_ATTR_TEMPERATURE 0x80
#define THERMOSTAT_ATTR_TARGET_TEMPERATURE 0x81
#define THERMOSTAT_ATTR_THRESHOLD_HIGH 0x82
#define THERMOSTAT_ATTR_THRESHOLD_LOW 0x83
#define THERMOSTAT_ATTR_MAX_HEAT_TIME 0x84
#define THERMOSTAT_ATTR_MIN_COOLDOWN_TIME 0x85
#define THERMOSTAT_ATTR_HUMIDITY 0x86
#define THERMOSTAT_ATTR_TEMPERATURE_CORRECTION 0x87
#define THERMOSTAT_ATTR_HUMIDITY_CORRECTION 0x88
#define THERMOSTAT_ATTR_THERMOMETER_COUNT 0x89
#define THERMOSTAT_ATTR_HUMIDITY_SENSOR_COUNT 0x8A

#define IRRIGATION_ATTR_PLANT_ENABLE 0x80
#define IRRIGATION_ATTR_SENSOR_COUNT 0x81
#define IRRIGATION_ATTR_MOISTURE_0 0x82
#define IRRIGATION_ATTR_MOISTURE_1 0x83
#define IRRIGATION_ATTR_MOISTURE_2 0x84
#define IRRIGATION_ATTR_TARGET_MOISTURE_0 0x85
#define IRRIGATION_ATTR_TARGET_MOISTURE_1 0x86
#define IRRIGATION_ATTR_TARGET_MOISTURE_2 0x87
#define IRRIGATION_ATTR_MOISTURE_LOW_0 0x88
#define IRRIGATION_ATTR_MOISTURE_LOW_1 0x89
#define IRRIGATION_ATTR_MOISTURE_LOW_2 0x8A
#define IRRIGATION_ATTR_MOISTURE_LOW_DELAY_0 0x8B
#define IRRIGATION_ATTR_MOISTURE_LOW_DELAY_1 0x8C
#define IRRIGATION_ATTR_MOISTURE_LOW_DELAY_2 0x8D
#define IRRIGATION_ATTR_SENSOR_RAW_0 0x8E
#define IRRIGATION_ATTR_SENSOR_RAW_1 0x8F
#define IRRIGATION_ATTR_SENSOR_RAW_2 0x90
#define IRRIGATION_ATTR_SENSOR_RAW_MAX_0 0x91
#define IRRIGATION_ATTR_SENSOR_RAW_MAX_1 0x92
#define IRRIGATION_ATTR_SENSOR_RAW_MAX_2 0x93
#define IRRIGATION_ATTR_SENSOR_RAW_MIN_0 0x94
#define IRRIGATION_ATTR_SENSOR_RAW_MIN_1 0x95
#define IRRIGATION_ATTR_SENSOR_RAW_MIN_2 0x96
#define IRRIGATION_ATTR_MOISTURE_CHANGE_HYSTERESIS_TIME 0x97
#define IRRIGATION_ATTR_MOISTURE_CHANGE_HYSTERESIS_AMOUNT 0x98
#define IRRIGATION_ATTR_CALIBRATION_MODE 0x99
#define IRRIGATION_ATTR_SENSOR_RECORDED_MAX_0 0x9A
#define IRRIGATION_ATTR_SENSOR_RECORDED_MAX_1 0x9B
#define IRRIGATION_ATTR_SENSOR_RECORDED_MAX_2 0x9C
#define IRRIGATION_ATTR_SENSOR_RECORDED_MIN_0 0x9D
#define IRRIGATION_ATTR_SENSOR_RECORDED_MIN_1 0x9E
#define IRRIGATION_ATTR_SENSOR_RECORDED_MIN_2 0x9F

#define CAMERA_ATTR_NOTIFICATION_ENABLE 0x80
#define CAMERA_ATTR_MOTION_SENSITIVITY 0x81
#define CAMERA_ATTR_IDLE_RETURN_TIME 0x82

#endif
