// EEPROM adress offsets for static and dynamic configs.

#define GENERIC_EEPROM_ADDR_TYPE 8
#define GENERIC_EEPROM_ADDR_ID 9

#define GENERIC_EEPROM_ADDR_APP_INTERVAL 16

// ---- Power Outlet
#define POWER_OUTLET_EEPROM_ADDR_SOCKET_COUNT 256
#define POWER_OUTLET_EEPROM_ADDR_VALUES_INVERTED 257


// ---- Thermostat


// ---- Irrigation
#define IRRIGATION_EEPROM_ADDR_SENSOR_MUX 256
#define IRRIGATION_EEPROM_ADDR_SENSOR_COUNT 257

// Reserve 6 words for config of up to 6 sensors
#define IRRIGATION_EEPROM_ADDR_SENSOR_RAW_MAX 258
#define IRRIGATION_EEPROM_ADDR_SENSOR_RAW_MIN 270
#define IRRIGATION_EEPROM_ADDR_SENSOR_CALIBRATION 282
#define IRRIGATION_EEPROM_ADDR_TARGET_MOISTURE 294
#define IRRIGATION_EEPROM_ADDR_MOISTURE_LOW_DELAY 306
#define IRRIGATION_EEPROM_ADDR_MIN_COOLDOWN 318
