// EEPROM adress offsets for static HW configs.

#define GENERIC_EEPROM_ADDR_TYPE 8
#define GENERIC_EEPROM_ADDR_ID 9

// ---- Power Outlet
#define POWEROUTLET_EEPROM_ADDR_SOCKET_COUNT 256
#define POWEROUTLET_EEPROM_ADDR_VALUES_INVERTED 257

// ---- Thermostat
#define THERMOSTAT_EEPROM_ADDR_HUMIDITY_SENSOR_COUNT 256

// ---- Irrigation
#define IRRIGATION_EEPROM_ADDR_SENSOR_MUX 256
#define IRRIGATION_EEPROM_ADDR_SENSOR_COUNT 257
// Reserve 6 words for config of up to 6 sensors
//#define IRRIGATION_EEPROM_ADDR_SENSOR_RAW_MAX 258
//#define IRRIGATION_EEPROM_ADDR_SENSOR_RAW_MIN 270
//#define IRRIGATION_EEPROM_ADDR_SENSOR_CALIBRATION 282
//#define IRRIGATION_EEPROM_ADDR_TARGET_MOISTURE 294
//#define IRRIGATION_EEPROM_ADDR_MOISTURE_LOW_DELAY 306
//#define IRRIGATION_EEPROM_ADDR_MIN_COOLDOWN 318

// Reserve addresses 512 + for application state
