#ifndef SH_DEVICE_DEFINITION_H
#define SH_DEVICE_DEFINITION_H

#include <stdint.h>

#if defined (__AVR_ATmega328P__)
	#define EEPROM_ADDR_TYPE 8
	#define EEPROM_ADDR_ID 9
#endif

struct sh_device_metadata {
	uint8_t type;
	uint8_t id;
};

/*
	Device type enumeration.
*/
#define SH_TYPE_NULL 0
#define SH_TYPE_RESERVED_1 1
#define SH_TYPE_RESERVED_2 2
#define SH_TYPE_RESERVED_3 3
#define SH_TYPE_RESERVED_4 4
#define SH_TYPE_RESERVED_5 5
#define SH_TYPE_IRRIGATION 6
#define SH_TYPE_POWEROUTLET 7
#define SH_TYPE_THERMOSTAT 8
#define SH_TYPE_CAMERA 9

/*
	Registers per device.
	All vlues are passed as integers but may not represent integers in device units.
*/
#define GENERIC_REG_NULL 0
#define GENERIC_REG_RESERVED_1 1
#define GENERIC_REG_RESERVED_2 2
#define GENERIC_REG_RESERVED_3 3
#define GENERIC_REG_RESERVED_4 4
#define GENERIC_REG_RESERVED_5 5
#define GENERIC_REG_ENABLE 6
#define GENERIC_REG_PING 7
//#define GENERIC_REG_KEEPALIVE 8
#define GENERIC_REG_DATE 9
#define GENERIC_REG_TIME 10
//#define GENERIC_REG_WEEKDAY 11 // Can fit in one byte of the date register
#define GENERIC_REG_SCHEDULE 12
#define GENERIC_REG_SCHEDULE_ENABLE 13
#define GENERIC_REG_SCHEDULE_COUNT 14
#define GENERIC_REG_APP_FREQUENCY 20
#define GENERIC_REG_POLL_FREQUENCY 21
#define GENERIC_REG_PUSH_ENABLE 31
#define GENERIC_REG_PUSH_FREQUENCY 32
#define GENERIC_REG_PUSH_BUFFERING 33

#define POWEROUTLET_REG_STATE 101
#define POWEROUTLET_REG_SOCKET_COUNT 102

#define THERMOSTAT_REG_TEMPERATURE 101
#define THERMOSTAT_REG_TARGET_TEMPERATURE 102
#define THERMOSTAT_REG_THRESHOLD_HIGH 103
#define THERMOSTAT_REG_THRESHOLD_LOW 104
#define THERMOSTAT_REG_HYSTERESIS 105
#define THERMOSTAT_REG_MIN_COOLDOWN 106
#define THERMOSTAT_REG_HUMIDITY 107

#define IRRIGATION_REG_MOISTURE 101
#define IRRIGATION_REG_TARGET_MOISTURE 102
#define IRRIGATION_REG_THRESHOLD_HIGH 103
#define IRRIGATION_REG_THRESHOLD_LOW 104
#define IRRIGATION_REG_HYSTERESIS 105
#define IRRIGATION_REG_MIN_COOLDOWN 106
#define IRRIGATION_REG_SWITCH_COUNTER 107

#endif
