#ifndef SH_DEVICE_DEFINITION_H
#define SH_DEVICE_DEFINITION_H

#include <stdint.h>

struct sh_device_metadata {
	uint8_t type;
	uint8_t id;
};

/*
	Device type enumeration.
*/
#define SH_TYPE_NULL 0x00
#define SH_TYPE_RESERVED_1 0x01
#define SH_TYPE_RESERVED_2 0x02
#define SH_TYPE_RESERVED_3 0x03
#define SH_TYPE_RESERVED_4 0x04
#define SH_TYPE_RESERVED_5 0x05
#define SH_TYPE_IRRIGATION 0x06
#define SH_TYPE_POWEROUTLET 0x07
#define SH_TYPE_THERMOSTAT 0x08
#define SH_TYPE_CAMERA 0x09

/*
	Registers common to all devices.
*/
#define GENERIC_REG_NULL 0x01
#define GENERIC_REG_RESERVED_1 0x01
#define GENERIC_REG_RESERVED_2 0x02
#define GENERIC_REG_RESERVED_3 0x03
#define GENERIC_REG_RESERVED_4 0x04
#define GENERIC_REG_RESERVED_5 0x05
#define GENERIC_REG_ENABLE 0x06
#define GENERIC_REG_PING 0x07
//#define GENERIC_REG_KEEPALIVE 0x08
/*
#define GENERIC_REG_DATE 0x09
#define GENERIC_REG_TIME 0x0A
#define GENERIC_REG_WEEKDAY 0x0B // Can fit in one byte of the date register
#define GENERIC_REG_SCHEDULE 0x0C
#define GENERIC_REG_SCHEDULE_ENABLE 0x0D
#define GENERIC_REG_SCHEDULE_COUNT 0x0E
*/
#define GENERIC_REG_BLINK 0x0F
#define GENERIC_REG_APP_INTERVAL 0x10
#define GENERIC_REG_POLL_INTERVAL 0x11
#define GENERIC_REG_PUSH_ENABLE 0x12
#define GENERIC_REG_PUSH_INTERVAL 0x13
#define GENERIC_REG_PUSH_BUFFERING 0x14
#define GENERIC_REG_RESET_CONFIGS 0x15


/*
	Device-specific registers. 
*/
#define POWEROUTLET_REG_STATE 0x80
#define POWEROUTLET_REG_SOCKET_COUNT 0x81

#define THERMOSTAT_REG_TEMPERATURE 0x80
#define THERMOSTAT_REG_TARGET_TEMPERATURE 0x81
#define THERMOSTAT_REG_THRESHOLD_HIGH 0x82
#define THERMOSTAT_REG_THRESHOLD_LOW 0x88
#define THERMOSTAT_REG_MAX_HEAT_TIME 0x84
#define THERMOSTAT_REG_MIN_COOLDOWN_TIME 0x85
#define THERMOSTAT_REG_HUMIDITY 0x86
#define THERMOSTAT_REG_TEMPERATURE_CORRECTION 0x87
#define THERMOSTAT_REG_HUMIDITY_CORRECTION 0x88
#define THERMOSTAT_REG_THERMOMETER_COUNT 0x89
#define THERMOSTAT_REG_HUMIDITY_SENSOR_COUNT 0x8A

#define IRRIGATION_REG_PLANT_ENABLE 0x80
#define IRRIGATION_REG_SENSOR_COUNT 0x81
#define IRRIGATION_REG_MOISTURE_0 0x82
#define IRRIGATION_REG_MOISTURE_1 0x83
#define IRRIGATION_REG_MOISTURE_2 0x84
#define IRRIGATION_REG_TARGET_MOISTURE_0 0x85
#define IRRIGATION_REG_TARGET_MOISTURE_1 0x86
#define IRRIGATION_REG_TARGET_MOISTURE_2 0x87
#define IRRIGATION_REG_MOISTURE_LOW_0 0x88
#define IRRIGATION_REG_MOISTURE_LOW_1 0x89
#define IRRIGATION_REG_MOISTURE_LOW_2 0x8A
#define IRRIGATION_REG_MOISTURE_LOW_DELAY_0 0x8B
#define IRRIGATION_REG_MOISTURE_LOW_DELAY_1 0x8C
#define IRRIGATION_REG_MOISTURE_LOW_DELAY_2 0x8D
#define IRRIGATION_REG_SENSOR_RAW_0 0x8E
#define IRRIGATION_REG_SENSOR_RAW_1 0x8F
#define IRRIGATION_REG_SENSOR_RAW_2 0x90
#define IRRIGATION_REG_SENSOR_RAW_MAX_0 0x91
#define IRRIGATION_REG_SENSOR_RAW_MAX_1 0x92
#define IRRIGATION_REG_SENSOR_RAW_MAX_2 0x93
#define IRRIGATION_REG_SENSOR_RAW_MIN_0 0x94
#define IRRIGATION_REG_SENSOR_RAW_MIN_1 0x95
#define IRRIGATION_REG_SENSOR_RAW_MIN_2 0x96
#define IRRIGATION_REG_MOISTURE_CHANGE_HYSTERESIS_TIME 0x97
#define IRRIGATION_REG_MOISTURE_CHANGE_HYSTERESIS_AMOUNT 0x98
#define IRRIGATION_REG_CALIBRATION_MODE 0x99
#define IRRIGATION_REG_SENSOR_RECORDED_MAX_0 0x9A
#define IRRIGATION_REG_SENSOR_RECORDED_MAX_1 0x9B
#define IRRIGATION_REG_SENSOR_RECORDED_MAX_2 0x9C
#define IRRIGATION_REG_SENSOR_RECORDED_MIN_0 0x9D
#define IRRIGATION_REG_SENSOR_RECORDED_MIN_1 0x9E
#define IRRIGATION_REG_SENSOR_RECORDED_MIN_2 0x9F


#endif
